version: '3.4'
services:
  db:
    image: postgres:14.10
    user: root
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=Omar@012
      - POSTGRES_DB=postgres
    restart: always
    volumes:
        - ./postgresql:/var/lib/postgresql/data
    mem_limit: 6g  # تحديد الحد الأقصى للذاكرة 6 جيجابايت
    cpus: 6      # تحديد عدد الأنوية المستخدمة بـ 12 كور
  odoo17:
    #image: odoo:17.0
    image: odooo-18.0 

    user: root
    depends_on:
      - db
    ports:
      - "10019:8069"  # منفذ واجهة Odoo
      - "20014:8072"  # منفذ الدردشة الحية
    tty: true
    command: --
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=Omar@012
    volumes:
      - ./addons:/mnt/extra-addons
      - ./enterprise:/mnt/enterprise
      - ./etc:/etc/odoo
  #    - ./entrypoint.sh:/entrypoint.sh
    restart: always
    mem_limit: 6g  # تحديد الحد الأقصى للذاكرة 6 جيجابايت
    cpus: 6      # تحديد عدد الأنوية المستخدمة بـ 12 كور

  # pgadmin:
  #   image: fenglc/pgadmin4
  #   ports:
  #     - 5051:5051
  #   restart: always
  #   depends_on:
  #     - db
  #   environment:
  #     DEFAULT_USER: mahmoud
  #     DEFAULT_PASSWORD: Omar012
  #   volumes:
  #     - ./pgadmin-data:/var/lib/pgadmin
